/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
Title: Tenhun Falling spaceman (FanArt)
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useMotionValue, useSpring } from "motion/react";
import { useFrame } from "@react-three/fiber";

export function Ghost(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/ghost_in_the_shell_cyborg_head.glb')
  const { actions } = useAnimations(animations, group)
  const [isDragging, setIsDragging] = useState(false)
  const [previousMousePosition, setPreviousMousePosition] = useState({ x: 0, y: 0 })

  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 30 });
  useEffect(() => {
    ySpring.set(-1);
  }, [ySpring]);

  // Handle mouse drag rotation
  useEffect(() => {
    const handleMouseDown = (event) => {
      setIsDragging(true);
      setPreviousMousePosition({ x: event.clientX, y: event.clientY });
    };

    const handleMouseMove = (event) => {
      if (isDragging && group.current) {
        const deltaX = event.clientX - previousMousePosition.x;
        const deltaY = event.clientY - previousMousePosition.y;
        
        // Rotate around Y-axis based on horizontal mouse movement
        group.current.rotation.y += deltaX * 0.003;
        
        // Rotate around X-axis based on vertical mouse movement (optional)
        group.current.rotation.x += deltaY * 0.003;
        
        setPreviousMousePosition({ x: event.clientX, y: event.clientY });
      }
    };

    const handleMouseUp = () => {
      setIsDragging(false);
    };


    // Add event listeners
    window.addEventListener('mousedown', handleMouseDown);
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    
    
    // Cleanup
    return () => {
      window.removeEventListener('mousedown', handleMouseDown);
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    };
  }, [isDragging, previousMousePosition]);

  // Handle scroll rotation
  useEffect(() => {
    const handleWheel = (event) => {
      if (group.current && !isDragging) {
        // Rotate around Y-axis based on scroll direction
        const rotationSpeed = 0.002;
        if (event.deltaY > 0) {
          // Scroll down - rotate clockwise
          group.current.rotation.y += rotationSpeed;
        } else {
          // Scroll up - rotate counter-clockwise
          group.current.rotation.y -= rotationSpeed;
        }
      }
    };

    // Add event listener to the window
    window.addEventListener('wheel', handleWheel);
    
    // Cleanup
    return () => {
      window.removeEventListener('wheel', handleWheel);
    };
  }, [isDragging]);

  useFrame(() => {
    group.current.position.y = ySpring.get();
  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={props.rotation || [-0.9, Math.PI / 1.5, 0.12]}
      scale={props.scale || 1.2}
      position={props.position || [3, 0, 0]}
      style={{ cursor: isDragging ? 'grabbing' : 'grab' }}
    >
       <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.005}>
          <group name="c80305373e16494482736b61b620e337fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="SideRot001_low"
                  position={[-65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="SideRot001_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideRot001_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="SideRot002_low"
                  position={[-65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="SideRot002_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideRot002_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="SideRot003_low"
                  position={[-65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="SideRot003_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideRot003_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="SideRot_low"
                  position={[-65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="SideRot_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideRot_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="sideRight_low"
                  position={[65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="sideRight_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.sideRight_low_Head_0.geometry}
                    material={materials.Head}
                  />
                  <group name="SideRot004_lowRight">
                    <mesh
                      name="SideRot004_lowRight_Head_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.SideRot004_lowRight_Head_0.geometry}
                      material={materials.Head}
                    />
                  </group>
                </group>
                <group
                  name="side_low"
                  position={[-65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="side_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.side_low_Head_0.geometry}
                    material={materials.Head}
                  />
                  <group name="SideRot004_low">
                    <mesh
                      name="SideRot004_low_Head_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.SideRot004_low_Head_0.geometry}
                      material={materials.Head}
                    />
                  </group>
                </group>
                <group
                  name="SideRot_lowRight"
                  position={[65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="SideRot_lowRight_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideRot_lowRight_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="SideRot001_lowRight"
                  position={[65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="SideRot001_lowRight_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideRot001_lowRight_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="SideRot002_lowRight"
                  position={[65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="SideRot002_lowRight_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideRot002_lowRight_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="SideRot003_lowRight"
                  position={[65.341, 111.463, 9.877]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="SideRot003_lowRight_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideRot003_lowRight_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="TopRot002_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="TopRot002_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.TopRot002_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="TopRot_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="TopRot_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.TopRot_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="Top_low"
                  position={[0, 65.478, 61.525]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="Top_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Top_low_Head_0.geometry}
                    material={materials.Head}
                  />
                  <group name="TopInner_low" position={[0, 0.615, -0.655]}>
                    <mesh
                      name="TopInner_low_Head_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TopInner_low_Head_0.geometry}
                      material={materials.Head}
                    />
                  </group>
                  <group name="TopRot001_low" position={[0, 0.615, -0.655]}>
                    <mesh
                      name="TopRot001_low_Head_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TopRot001_low_Head_0.geometry}
                      material={materials.Head}
                    />
                  </group>
                  <group name="TopRot001_lowRigt" position={[0, 0.615, -0.655]}>
                    <mesh
                      name="TopRot001_lowRigt_Head_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.TopRot001_lowRigt_Head_0.geometry}
                      material={materials.Head}
                    />
                  </group>
                </group>
                <group name="TopRot002_lowRigt" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="TopRot002_lowRigt_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.TopRot002_lowRigt_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="TopRot_lowRigt" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="TopRot_lowRigt_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.TopRot_lowRigt_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="BottomSideRight_low"
                  position={[54.574, 46.296, 21]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="BottomSideRight_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.BottomSideRight_low_Head_0.geometry}
                    material={materials.Head}
                  />
                  <group name="BottomSideRot_lowRight">
                    <mesh
                      name="BottomSideRot_lowRight_Head_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BottomSideRot_lowRight_Head_0.geometry}
                      material={materials.Head}
                    />
                  </group>
                </group>
                <group
                  name="BottomSideRot001_low"
                  position={[-54.447, 46.468, 20.982]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="BottomSideRot001_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.BottomSideRot001_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="BottomSide_low"
                  position={[-54.574, 46.296, 21]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="BottomSide_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.BottomSide_low_Head_0.geometry}
                    material={materials.Head}
                  />
                  <group name="BottomSideRot_low">
                    <mesh
                      name="BottomSideRot_low_Head_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.BottomSideRot_low_Head_0.geometry}
                      material={materials.Head}
                    />
                  </group>
                </group>
                <group
                  name="BottomSideRot001_lowRight"
                  position={[59.678, 39.345, 21.755]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="BottomSideRot001_lowRight_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.BottomSideRot001_lowRight_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="Eyes_low"
                  position={[0, 122.895, -23.015]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={8.159}>
                  <mesh
                    name="Eyes_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Eyes_low_Head_0.geometry}
                    material={materials.Head}
                  />
                  <group name="EyesRot001_low" scale={12.256}>
                    <mesh
                      name="EyesRot001_low_Head_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.EyesRot001_low_Head_0.geometry}
                      material={materials.Head}
                    />
                  </group>
                  <group name="EyesRot_low" scale={12.256}>
                    <mesh
                      name="EyesRot_low_Head_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.EyesRot_low_Head_0.geometry}
                      material={materials.Head}
                    />
                  </group>
                </group>
                <group
                  name="EyesRot001_low001"
                  position={[-56.565, 122.733, -15.334]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="EyesRot001_low001_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.EyesRot001_low001_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="EyesRot001_low002"
                  position={[56.565, 122.733, -15.334]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <mesh
                    name="EyesRot001_low002_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.EyesRot001_low002_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="Back_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="Back_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Back_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="BackBottom_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="BackBottom_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.BackBottom_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="BrainHolder_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="BrainHolder_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.BrainHolder_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="BrainWireCon_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="BrainWireCon_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.BrainWireCon_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="BrainWiresFat_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="BrainWiresFat_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.BrainWiresFat_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="BrainWiresThin_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="BrainWiresThin_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.BrainWiresThin_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="Brain_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="Brain_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Brain_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="Ear_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="Ear_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Ear_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="Inside_face_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="Inside_face_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Inside_face_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="Mouth_low" rotation={[-Math.PI / 2, 0, 0]} scale={8.159}>
                  <mesh
                    name="Mouth_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mouth_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group name="inside_low" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh
                    name="inside_low_Head_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.inside_low_Head_0.geometry}
                    material={materials.Head}
                  />
                </group>
                <group
                  name="Plane002"
                  position={[0, 8.582, 4.912]}
                  rotation={[Math.PI, -Math.PI / 4, 0]}
                  scale={24.619}>
                  <mesh
                    name="Plane002_Holograms_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane002_Holograms_0.geometry}
                    material={materials.Holograms}
                  />
                </group>
                <group
                  name="Sphere002"
                  position={[0, 98.266, 19.255]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={335.261}>
                  <mesh
                    name="Sphere002_Holograms_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere002_Holograms_0.geometry}
                    material={materials.Holograms}
                  />
                </group>
                <group
                  name="Plane003"
                  position={[0, 8.582, 4.912]}
                  rotation={[0, -Math.PI / 4, 0]}
                  scale={[24.619, 24.618, 24.619]}>
                  <mesh
                    name="Plane003_Holograms_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane003_Holograms_0.geometry}
                    material={materials.Holograms}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/ghost_in_the_shell_cyborg_head.glb')
